---
# Site metadata
site_name: Git@HOGENT gebruikersgids
site_url: "https://hogenttin.github.io/git-hogent-gids/"
repo_name: "HoGentTIN/git-hogent-gids/"
repo_url: "https://github.com/HoGentTIN/git-hogent-gids/"
edit_uri: edit/main/docs/

# Navigation
nav:
  - "Inhoud": "index.md"
  - "1TI":
    - "Semester 1": "semester-1.md"
    - "Semester 2": "semester-2.md"
  - "2TI":
    - "Semester 3": "semester-3.md"
    - "Semester 4": "semester-4.md"
  - "3TI":
    - "Semester 5": "semester-5.md"
    - "Semester 6": "semester-6.md"
  - "Achtergrondinfo": "achtergrondinfo.md"

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  # syntax highlighting:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Theme settings
theme:
  name: material
  features:
    - navigation.expand
    - content.code.copy
    - content.code.select
    - content.action.edit
  favicon: "https://www.hogent.be/themes/hogent/images/ico/favicon.ico"
  logo: "https://img.icons8.com/ios-filled/2x/ffffff/github.png"
  font:
    text: "Montserrat"
    code: "Inconsolata"
  language: "nl"
  icon:
    edit: material/pencil 
    view: material/eye

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
